version: "3"

services:
  server:
    build: ./
    ports:
      - 8181:8181
    depends_on:
      - mongodb
    environment:
      - DATABASE_HOST=mongodb
    volumes:
      - ./public:/usr/src/app/public
  nginx:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./public:/public
    depends_on:
      - server
  mongodb:
    image: mongo:latest
    ports:
      - 8282:27017
    volumes:
      - mongodb:/data/db
volumes:
  mongodb:
    driver: local